#!/bin/bash
# Updated Excel Export Features

echo "================================"
echo "✅ Combined Excel Export Updated"
echo "================================"
echo ""

echo "📋 NEW FEATURES:"
echo ""
echo "1️⃣  SINGLE FILE → Single Excel"
echo "   Command: python3 nessus-report-gen.py"
echo "   - Select: Option 3 (Excel)"
echo "   - Input: Single .nessus file"
echo "   - Output: One Excel file with all data"
echo ""

echo "2️⃣  MULTIPLE FILES → One Combined Excel ✨ NEW"
echo "   Command: python3 nessus-report-gen.py"
echo "   - Select: Option 3 (Excel)"
echo "   - Input: Folder path with .nessus files"
echo "   - Output Mode: 1 (Combined)"
echo "   - Output: ONE Excel file with all reports"
echo ""

echo "3️⃣  MULTIPLE FILES → Separate Excels"
echo "   Command: python3 nessus-report-gen.py"
echo "   - Select: Option 3 (Excel)"
echo "   - Input: Folder path"
echo "   - Output Mode: 2 (Separate)"
echo "   - Output: One Excel per .nessus file"
echo ""

echo "📊 COMBINED EXCEL STRUCTURE:"
echo ""
echo "   ┌─────────────────────────────────┐"
echo "   │ 📄 File: scan1.nessus (Green)   │  ← File header (bright green)"
echo "   ├─────────────────────────────────┤"
echo "   │ IP | Check | Level | Desc | ... │  ← Blue headers"
echo "   ├─────────────────────────────────┤"
echo "   │ Data rows...                    │"
echo "   ├─────────────────────────────────┤"
echo "   │ (BLANK ROW SEPARATOR)           │  ← 1 row spacing"
echo "   ├─────────────────────────────────┤"
echo "   │ 📄 File: scan2.nessus (Green)   │  ← Next file"
echo "   ├─────────────────────────────────┤"
echo "   │ IP | Check | Level | Desc | ... │"
echo "   ├─────────────────────────────────┤"
echo "   │ Data rows...                    │"
echo "   └─────────────────────────────────┘"
echo ""

echo "🎨 COLOR SCHEME:"
echo "   🟢 Green Header: File names & separators"
echo "   🔵 Blue Header: Column headers"
echo "   ⚪ White Data: Compliance details"
echo ""

echo "📑 10 COLUMNS IN EACH SECTION:"
echo "   1. IP Address"
echo "   2. Check Number"
echo "   3. Level (L1/L2)"
echo "   4. Description"
echo "   5. Result"
echo "   6. Info"
echo "   7. Solution"
echo "   8. Impact"
echo "   9. Policy Value"
echo "   10. Configured Value"
echo ""

echo "✨ FEATURES:"
echo "   ✅ Professional formatting"
echo "   ✅ Borders on all cells"
echo "   ✅ Text wrapping for long content"
echo "   ✅ Optimized column widths"
echo "   ✅ Blank row separation between reports"
echo "   ✅ Distinct file headers"
echo "   ✅ L1/L2 filtering support"
echo ""

echo "🚀 QUICK START:"
echo "   python3 nessus-report-gen.py"
echo ""
